# Generated by Django 3.2.9 on 2021-11-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentHyperparameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epsilon', models.DecimalField(decimal_places=18, max_digits=20)),
                ('epsilon_decay', models.DecimalField(decimal_places=8, default=0.9995, max_digits=10)),
                ('epsilon_min', models.DecimalField(decimal_places=8, default=0.05, max_digits=10)),
                ('gamma', models.DecimalField(decimal_places=4, default=0.9, max_digits=5)),
                ('learning_rate', models.DecimalField(decimal_places=9, default=0.0025, max_digits=10)),
                ('batch_size', models.IntegerField(default=256)),
                ('learns', models.IntegerField(default=0)),
                ('averageRewardList', models.JSONField(default={})),
                ('agent', models.IntegerField()),
                ('bestReward', models.DecimalField(decimal_places=20, max_digits=40)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_memory_len', models.IntegerField(default=100000)),
                ('agent', models.IntegerField()),
                ('states', models.JSONField(default={})),
                ('actions', models.JSONField(default={})),
                ('rewards', models.JSONField(default={})),
                ('next_states', models.JSONField(default={})),
                ('dones', models.JSONField(default={})),
            ],
        ),
    ]
