# Generated by Django 3.2.9 on 2021-11-19 03:56

from django.db import migrations
import json

def populate_db(apps, schema_editor):
    AgentHyperParameters = apps.get_model("smashBot", "AgentHyperparameters")
    Memory = apps.get_model("smashBot", "Memory")

    # agent1parameters = AgentHyperParameters(agent=1, bestReward=0, epsilon=1)
    agent2parameters = AgentHyperParameters(agent=2, bestReward=0, epsilon=1)

    # agent1Memory = Memory(agent=1, states=json.dumps([]), actions=json.dumps([]), rewards=json.dumps([]), next_states=json.dumps([[]]), dones=json.dumps([]))
    agent2Memory = Memory(agent=2, states=json.dumps([]), actions=json.dumps([]), rewards=json.dumps([]), next_states=json.dumps([]), dones=json.dumps([]), previous_actions=json.dumps([]))

    # agent1parameters.save()
    agent2parameters.save()

    # agent1Memory.save()
    agent2Memory.save()


class Migration(migrations.Migration):

    dependencies = [
        ('smashBot', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
